Add missing dimensions to `Model.Dims()` for MIMO systems
milosgajdos/go-estimate pull request #8
Opened 2021-05-23 13:55 UTC by soypat

There was a mistake in `sim` package in that there was no distinction made between input vector length (`u`) and state vector length (`x`). Model dimension now is fully explicit returning length of `x` state vector, `u` input vector, `y` output vector, and `z` disturbance input vector. Do note that I have yet to implement the disturbance matrix `E` so for now the fourth parameter returned by `Dims()` should be equal to length of `x` (first parameter). I just thought it was a good idea to future-proof the API.

I've also added documentation to interfaces.

2021-05-25 19:26 UTC, soypat commented on filter.go
> +	// Predict returns the expected change in internal state
Whoops, this is wrong, it's not the change!

2021-05-26 07:51 UTC, milosgajdos requested changes
First of all, thanks for the fantastic work on this. Changes generally look good to me, but I do have 2 nits:
1. `*invalidModel` `Dims()` method returns 4 values, 2 of which are always 0 and not used at all. Besides this, `Dims()` method can become very confusing going forward given `Dims` methods from `gonum` always return only 2 values. I'd like to avoid the confusion as it's unnecessarily induced.
2. Prefixing local vars with underscores `_` is not idiomatic `Go`. I'd definitely want to avoid doing that in the codebase.

2021-05-26 07:51 UTC, milosgajdos commented on filter.go
> +	SystemMatrix() (A mat.Matrix) // TODO rename to SystemMatrix
Can you remove these TODOs?

2021-05-26 11:14 UTC, soypat commented on filter.go
> +	SystemMatrix() (A mat.Matrix) // TODO rename to SystemMatrix
Yes! Forgot about them

2021-05-26 11:44 UTC, soypat commented
Replying to your nits
1. There is a real need to using `nx`, `ny` and `nu` as returned by `Dims()`, without the three one does not define a control system. You were missing the `nu` parameter before and doing some weird workaround in `Propagate()` where the input vector `u` had to have the same length as the output vector, which is (almost) always not the case. The way I see it we can:
   1. Rename `Dims()` to something like `SystemDims()` or `ControlDims()`
   2. Split `Dims()` into two functions, in which case we'd have to rename one or both.
   3. Remove `Dims()` and merge two interfaces `Model` and `DiscreteModel`, which I'm not even sure if is a good idea. I'm not that familiar with the library... yet
2. Consider it done!

2021-05-27 07:32 UTC, milosgajdos commented
Ok, I see what you mean. That's a reasonable request.

In that case, I'd prefer to call the func `SystemDims`/`ContolDims` -- just for the sake of avoiding confusion with the `gonum` API.

2021-05-27 20:03 UTC, soypat commented
Alright, changes incoming. I'd like to reply to a comment you made earlier:
> *invalidModel Dims() method returns 4 values, 2 of which are always 0 and not used at all. 

Yes, that is intentional. Dims() (_now SystemDims()_) returns `nx` state vector length, `ny` external/observed/output state, `nu` input vector length, and `nz` disturbance vector length. 

The disturbance matrix has not been implemented yet so `nz` is unused as of today.

`nx` and `ny` must be greater-than zero as you probably know. This is a requirement for any estimator to be able to predict internal state from incomplete measurements.

`nu` may be zero if the system does not have inputs. This is perfectly fine. It would mean the system is uncontrollable, which is undesirable in some cases while perfectly fine in others i.e. 

* airplane attitude+velocity as state which *should be controllable*
* a river's temperature, flow-rate and pollution whose state might be of interest but is fundamentally uncontrollable without harnessing serious hardware

2021-05-27 20:25 UTC, milosgajdos requested changes
Let's fix these linter errors and then we're ready to merge.

2021-05-28 08:11 UTC, merged

2021-05-28 13:41 UTC, soypat commented
@milosgajdos I forgot to make a new release. Looks like importing your package still uses old version.

2021-05-28 15:03 UTC, milosgajdos commented
I just cut `v0.1.0` release